apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    enableMetricsPlugin: true
    image: BROKER_K8S_IMAGE
    initImage: BROKER_INIT_IMAGE
  console:
    expose: true
